<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menus')->truncate();

        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => 'About',
                'url' => null,
                'icon' => 'fa fa-phone',
                'position' => 1,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-03-19 21:20:57',
                'updated_at' => '2025-04-07 02:42:03',
            ],
            [
                'id' => 2,
                'name' => 'Product',
                'url' => null,
                'icon' => null,
                'position' => 2,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:36:45',
                'updated_at' => '2025-04-08 06:30:36',
            ],
            [
                'id' => 3,
                'name' => 'Become A Seller',
                'url' => null,
                'icon' => null,
                'position' => 3,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:37:33',
                'updated_at' => '2025-04-08 06:30:29',
            ],
            [
                'id' => 4,
                'name' => 'Pages',
                'url' => null,
                'icon' => null,
                'position' => 4,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:38:24',
                'updated_at' => '2025-04-08 06:29:09',
            ],
            [
                'id' => 5,
                'name' => 'Blog',
                'url' => null,
                'icon' => null,
                'position' => 5,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:39:02',
                'updated_at' => '2025-04-08 06:30:12',
            ],
            [
                'id' => 6,
                'name' => 'Privacy & Policy',
                'url' => null,
                'icon' => null,
                'position' => 6,
                'parent_id' => 8,
                'parent_path' => '8',
                'menu_level' => 1,
                'menu_path' => 'Pages',
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:39:36',
                'updated_at' => '2025-04-08 06:29:58',
            ],
            [
                'id' => 7,
                'name' => 'Terms and conditions',
                'url' => null,
                'icon' => null,
                'position' => 7,
                'parent_id' => 8,
                'parent_path' => '8',
                'menu_level' => 1,
                'menu_path' => 'Pages',
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:40:19',
                'updated_at' => '2025-04-08 06:29:49',
            ],
            [
                'id' => 8,
                'name' => 'Faq',
                'url' => null,
                'icon' => null,
                'position' => 8,
                'parent_id' => 8,
                'parent_path' => '8',
                'menu_level' => 1,
                'menu_path' => 'Pages',
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:40:50',
                'updated_at' => '2025-04-08 06:29:31',
            ],
            [
                'id' => 9,
                'name' => 'Contact',
                'url' => null,
                'icon' => null,
                'position' => 9,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:41:11',
                'updated_at' => '2025-04-08 06:28:21',
            ],
            [
                'id' => 10,
                'name' => 'Home',
                'url' => null,
                'icon' => null,
                'position' => 10,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:50:01',
                'updated_at' => '2025-04-08 06:31:03',
            ],
            [
                'id' => 11,
                'name' => 'Test',
                'url' => null,
                'icon' => null,
                'position' => 11,
                'parent_id' => 10,
                'parent_path' => '8/10',
                'menu_level' => 2,
                'menu_path' => 'Pages/Privacy & Policy',
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-08 23:44:41',
                'updated_at' => '2025-04-08 23:44:41',
            ],
        ]);
    }
}
