services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.2/app
        ports:
            - "${APP_PORT:-80}:80"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mysql
            - redis

    mysql:
        image: "mysql:8.0"
        platform: "linux/x86_64"
        ports:
            - "${FORWARD_DB_PORT:-3307}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "biva_mart_mysql:/var/lib/mysql"
        networks:
            - sail

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        networks:
            - sail

    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "biva_mart_redis:/data"
        networks:
            - sail

    mailhog:
        image: "mailhog/mailhog:latest"
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    biva_mart_mysql:
        driver: local
    biva_mart_redis:
        driver: local
